import type { Metadata } from "next";
import { Manrope, Funnel_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const funnel = Funnel_Display({
  variable: "--font-funnel",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${funnel.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
